#!/usr/bin/env bash
# Install a global `dwellerd` command pointing at this project.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# root → /usr/local/bin (always on PATH), regular user → ~/.local/bin.
# Override either with: DWELLERD_BIN_DIR=/some/path make install-cli
if [ -n "${DWELLERD_BIN_DIR:-}" ]; then
    BIN_DIR="$DWELLERD_BIN_DIR"
elif [ "$(id -u)" -eq 0 ]; then
    BIN_DIR="/usr/local/bin"
else
    BIN_DIR="${HOME}/.local/bin"
fi
mkdir -p "$BIN_DIR"

CLI="$BIN_DIR/dwellerd"

cat > "$CLI" <<EOF
#!/usr/bin/env bash
# Dwellerd CLI shim — generated by deploy/scripts/install-cli.sh
# Edit $PROJECT_ROOT/Makefile for behavior changes; this is just dispatch.
PROJECT_ROOT="$PROJECT_ROOT"

ACTION="\${1:-setup}"
[ \$# -gt 0 ] && shift

case "\$ACTION" in
    -h|--help|help)
        cat <<USAGE
Usage: dwellerd [command]

Commands:
  setup               (default) interactive setup wizard
  run                 run Dwellerd in foreground
  bootstrap-user      create system user 'dwellerd' + groups (sudo)
  preflight           verify 'dwellerd' can reach docker / journal / dirs
  install-service     install as systemd service (User=dwellerd)
  uninstall-service   stop and remove systemd service
  start | stop | restart | status | logs
  clean               drop venv and __pycache__
  cd                  print project root (cd \\\$(dwellerd cd))
  help                show this help

Project: \$PROJECT_ROOT
USAGE
        ;;
    cd)
        echo "\$PROJECT_ROOT"
        ;;
    setup|run|run-web|start|stop|restart|status|logs|install-service|uninstall-service|install|clean|bootstrap-user|preflight|ensure-perms|fix-perms)
        exec make -C "\$PROJECT_ROOT" "\$ACTION" "\$@"
        ;;
    *)
        echo "dwellerd: unknown command '\$ACTION'" >&2
        echo "run 'dwellerd help' for usage" >&2
        exit 1
        ;;
esac
EOF
chmod +x "$CLI"

c_grn=$'\e[32m'; c_off=$'\e[0m'; c_dim=$'\e[2m'; c_ylw=$'\e[33m'

echo
echo "${c_grn}✓ installed:${c_off} $CLI"
echo "${c_dim}  project:${c_off}   $PROJECT_ROOT"
echo

case ":$PATH:" in
    *":$BIN_DIR:"*)
        echo "${c_grn}✓ $BIN_DIR is on PATH — try 'dwellerd help'${c_off}"
        ;;
    *)
        echo "${c_ylw}!${c_off} $BIN_DIR is not on your PATH yet."
        echo "  add this to your shell rc (~/.bashrc or ~/.zshrc):"
        echo
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo
        echo "  then reload:  source ~/.bashrc"
        ;;
esac
