"""Config writer — turns the wizard's answers into an annotated YAML file.

Hand-rolled rather than `yaml.dump` because the comments are the point:
this file is meant to be edited by hand afterwards, and a dumped mapping
with no explanation of what `crit: 90` means is a worse artifact than a
slightly longer writer.
"""
from __future__ import annotations

import shutil
import time
from pathlib import Path


def _q(value: str) -> str:
    """Quote a scalar for YAML, escaping the two characters that matter."""
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render(answers: dict) -> str:
    a = answers
    lines: list[str] = [
        "# Dwellerd configuration.",
        "# Edit by hand and restart the service: sudo systemctl restart dwellerd",
        f"# Generated by `dwellerd setup` on {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "telegram:",
        f"  bot_token: {_q(a['bot_token'])}",
        f"  chat_id: {_q(a['chat_id'])}",
        f"  lang: {a['lang']}                 # en | ru",
    ]
    if a.get("proxy"):
        lines.append(f"  proxy: {_q(a['proxy'])}")
    lines += [
        "",
        f"hostname: {_q(a['hostname'])}",
        "",
        "checks:",
        f"  interval: {a['interval']}              # seconds between every check",
        "",
        "  # Percentage checks. `warn` and `crit` are the levels at which an",
        "  # alert fires; set a block to `false` to turn that check off.",
        f"  cpu:    {{ warn: {a['warn']}, crit: {a['crit']} }}",
        f"  memory: {{ warn: {a['warn']}, crit: {a['crit']} }}",
        f"  swap:   {{ warn: {a['swap_warn']}, crit: {a['swap_crit']} }}",
        "",
        "  # Load average per core, so the numbers hold on any core count.",
        f"  load:   {{ warn: {a['load_warn']}, crit: {a['load_crit']} }}",
        "",
        "  disks:",
    ]
    for path in a["disks"]:
        lines.append(f"    - {{ path: {_q(path)}, warn: {a['warn']}, crit: {a['crit']} }}")

    lines.append("")
    if a["http"]:
        lines.append("  http:")
        for probe in a["http"]:
            lines.append(
                f"    - {{ name: {_q(probe['name'])}, url: {_q(probe['url'])}, "
                f"expect_status: {probe['expect_status']} }}"
            )
    else:
        lines += [
            "  # http:",
            '  #   - { name: api, url: "https://example.com/health", expect_status: 200 }',
        ]

    lines.append("")
    if a["systemd"]:
        lines.append("  systemd:")
        for unit in a["systemd"]:
            lines.append(f"    - {_q(unit)}")
    else:
        lines += ["  # systemd:", "  #   - nginx.service"]

    lines += [
        "",
        "  docker:",
        f"    enabled: {str(a['docker_enabled']).lower()}",
    ]
    if a["docker_containers"]:
        lines.append("    # Watch exactly these; one that disappears is an alert.")
        lines.append("    containers:")
        for name in a["docker_containers"]:
            lines.append(f"      - {_q(name)}")
    else:
        lines.append("    # Empty = watch whatever `docker ps -a` reports.")
        lines.append("    containers: []")
    lines.append("    # compose:")
    lines.append('    #   - "/opt/myapp/docker-compose.yaml"')

    lines += [
        "",
        "logs:",
        f"  enabled: {str(a['logs_enabled']).lower()}",
        "  notify: true            # false = keep capturing, stop the instant alerts",
        f"  level: {a['log_level']}            # all | info | warn | error",
        f"  digest_interval: {a['digest_interval']}   # seconds between digest messages",
        f"  retention_days: {a['retention_days']}",
        "  max_rows: 200000        # FIFO safety belt against a log storm",
    ]
    if a["log_sources"]:
        lines.append("  sources:")
        for source in a["log_sources"]:
            fields = [f"type: {source['type']}", f"name: {_q(source['name'])}"]
            for key in ("path", "unit", "container", "compose", "service"):
                if source.get(key):
                    fields.append(f"{key}: {_q(source[key])}")
            fields.append(f"pattern: {_q(source.get('pattern', '.+'))}")
            lines.append("    - { " + ", ".join(fields) + " }")
    else:
        lines += [
            "  sources: []",
            "  # sources:",
            '  #   - { type: docker_container, name: app, container: app, pattern: "ERROR|Traceback" }',
            '  #   - { type: file, name: nginx, path: "/var/log/nginx/error.log", pattern: "(?i)error" }',
            '  #   - { type: journal, name: sshd, unit: sshd.service, pattern: "(?i)fail" }',
        ]

    lines += [
        "",
        "report:",
        f"  enabled: {str(a['report_enabled']).lower()}",
        f"  interval: {a['report_interval']}       # seconds between status reports",
        "  # interfaces: [eth0]    # limit the network line to these NICs",
        "",
    ]
    return "\n".join(lines)


def write(path: Path, content: str) -> Path | None:
    """Write the config, backing up whatever was there. Returns the backup
    path, or None if there was nothing to back up."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    backup = None
    if path.exists():
        backup = path.with_suffix(f".yaml.bak-{time.strftime('%Y%m%d-%H%M%S')}")
        shutil.copy2(path, backup)
    tmp = path.with_suffix(".yaml.tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)          # atomic: no half-written config on a crash
    # The file holds a bot token: keep it off other users' eyes.
    path.chmod(0o600)
    return backup
